// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    attacker
    (
        init => init
        participate => participate
        drawWinnerAndFail => attack_async
        redeemPrize => reedem_prize
        drawWinner => draw_winner
        getLotteryScAddress => lottery_sc_address
    )
}

multiversx_sc_wasm_adapter::async_callback! { attacker }
