// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!(static64k);
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    erc1155
    (
        init => init
        createToken => create_token
        safe_transfer_from => safe_transfer_from
        safe_transfer_from_fungible => safe_transfer_from_fungible
        safe_transfer_from_non_fungible => safe_transfer_from_non_fungible
        batch_transfer_from => batch_transfer_from
        mint => mint
        burn => burn
        getTokenOwner => token_owner
        isFungible => is_fungible
        tokenTypeCreator => token_type_creator
        hasPermission => has_permission
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
